export {
  DashboardResponseSchema,
  DashboardCourseSchema,
  UpcomingAssignmentSchema,
  RecentFeedbackSchema,
  CourseProgressSchema,
  InstructorDashboardResponseSchema,
  InstructorCourseInfoSchema,
  InstructorRecentSubmissionSchema,
  type DashboardResponse,
  type DashboardCourse,
  type UpcomingAssignment,
  type RecentFeedback,
  type CourseProgress,
  type InstructorDashboardResponse,
  type InstructorCourseInfo,
  type InstructorRecentSubmission,
} from '@/features/dashboard/backend/schema';
